# Generated by Django 3.0.5 on 2020-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
